version: '2'
services:
    springjwt-app:
        image: springjwt
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://springjwt-mysql:3306/springjwt?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    springjwt-mysql:
        extends:
            file: mysql.yml
            service: springjwt-mysql
